### ISSUE TITLE
FakeXMLHttpRequest.restore sets window.XMLHttpRequest to undefined

### ISSUE THREAD

**Issue by darkscarletorchid** [thommyhh/fake-xmlhttprequest#1]
Hi, 
noticed the issue with removing FakeXMLHttpRequest,
When it is set up, it saves original object to **window.OriginalXHR** variable but,  on restore, retrieves it from  **window.originalXHR**, which doesn't store expected value. As a result, _window.XMLHttpRequest_ turns out to be _undefined._

FakeXMLHttpRequest.setup = function() {
    window.OriginalXHR = window.XMLHttpRequest;
    window.XMLHttpRequest = FakeXMLHttpRequest;
    FakeXMLHttpRequest.handlers = [];
};
FakeXMLHttpRequest.restore = function() {
    FakeXMLHttpRequest.handlers = [];
    window.XMLHttpRequest = window.originalXHR;
    delete window.originalXHR;
};

**Comment by thommyhh** [comment]
@darkscarletorchid Should be fixed with 1.2.1. Please try and provide feedback.

**Comment by darkscarletorchid** [comment]
@thommyhh Works fine with the fix. Thanks
