### ISSUE TITLE
[Bug?] Proxy request causes infinite loop

### ISSUE THREAD

**Issue by LostMyCode** [thommyhh/fake-xmlhttprequest#2]
If you add a handler that has `proxy` option like this 
```javascript
FakeXMLHttpRequest.addHandler({
    url: /projects\/(.*)\/services\/lostmycode/,
    proxy: (url, data) => {
        return "http://localhost:9090/" + url;
    }
});
```

you will get `maximum call stack size exceeded` error

```
Uncaught RangeError: Maximum call stack size exceeded
    at FakeXMLHttpRequest.open
```

So i think Line#166 should be `new window.OriginalXHR()` instead of `new XMLHttpRequest()`

https://github.com/thommyhh/fake-xmlhttprequest/blob/c4602cf1da63efda4f4a790808c2b5ac5e542bd6/lib/fake-xmlhttprequest.js#L165-L167

`new window.OriginalXHR()` worked for me

@thommyhh Sry for mentioning your old project. It's been 4 or 5 years since the last update, but I just wanted to help to improve this repo coz it really nice and helped me so much. Thank you.

**Comment by thommyhh** [comment]
@LostMyCode I'm sorry for the extremely late reply. I abandoned this, as there are better ways to solve the issue I tried to solve with this. Please see https://mswjs.io/.
